name: vacinefinder
description: Vacine Finder.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.20.0-nullsafety.3
  provider: ^5.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.5
  lottie: ^1.0.1
  firebase_messaging: "^9.1.3"
  firebase_core: "^1.1.0"
  syncfusion_flutter_calendar: ^19.1.59
  intl: any
  url_launcher: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  

 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700